language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: g5Cr/mHLMmagI+PUmFMpksTCVdxmUZckxU/EHMMcBt5HH3MRvsE0abO8jo/FaAtN53rIqgnuP2A9VJZD4aN/1wRpgZ4sqcYab1HjkjJ6NgVRyTnp0QLon1cELiO0TQgoqk7hoYzT9fktRlgsMii+Zjexkl6txocU9GKOJl5MpwAtt1oS1RtXjHzxOlbFQNixJ5uPs//MXQi+3HI+DwPVVqFSR0ZiCC+alr49d+GVx13iWslpe596/8j70PPI+kEoKRhxwnQ1GXXgOATcPLQgCemXHf/vH8JTXZPB/nJVmhUhd4xZaXk6+siESfI02Oootsps0L+qRhpk9lE51HSqo3yUvcB4beSW6OBw8KLYYexmowcVoAAY4of0fxPd93Fwklk3cwrCeOTvUn7LpmK6KZCpnkPUpxa7UwJoOVdYqUirBQyOsJLCZEdZos+cbebqWkYXTggEhUHpWCwqkJZQo54DNk4V26oT93gWLN3s+ieHc7VIoW0tpcPAMgGgWxHR3wbF5G0M/46UZx8TanlSoUWonjSbjswxOd8yrUltrEZm6xGngG8V+T+ZP5c4Wlapijk6Q1OlZmKOCfoUPvdY4j/Fa8nSbmWkD3WiSKbcWMCDrxib0/o5sMMX6KbZIkztfg9JFwYbffnHRyTIOGpseqmppvPx212T8MPdbE/LVD8=
  app: uncrowd-me
  on:
    repo: alouie1020/uncrowd-me-client
