language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: W4I6SpoVgeZK8ihNNhdvHJjrNXTcT1uEBwaP3SXbBAffC0y7SeLGCo+1RQgUMHABdz4EzBSpFDVU+YGT9BJlQXqqCQoX0jblBwt+WB8QUKgOMlDYIDITrq7SFyEJ7yHQ9P7/UmupU0lhlDt0b6Fzd7ETpsV91QS9cdMyNdgjRl2I2s0lGxlpLdV2TQEkjikU3nAkkkeWafn0o92JiphwF2oOBvPEYB63M7+dLpltmr7tF52voq04y+SGaw07tGv7ZtECbBYdwdxCKRQnVLbkPUAHN02NM5Tgu2DwIwCMwiCrd80jkxBJJEGBsNN8KOXnWMkiDpVzaxGdciy08yv2/iNEA2tt5+XzEilM/JVxXgvwVi+GRx9J94AeCsVaKM9nHw2A8raE/9SHgP61q6527rif14CzxUS9xDkUWCiUPMRtGC4F/A1pJwWqxaKtO0snzsscH9PdpKuBg5FL4yfg+ki0lQod///qPvG3cQseSMv6yCnMJ9xKAm7DmRjiji28qyLQKUWZMxMQZYoOaznl6ThSiV6+I2SHWRIRLcDaOrsGubxz5KYCTM0ku2RUBd79T11KeHY1IUrudoziUsjUozdPwRBm6WkLXoEYOwL3nQWpWLEgEnWfbm0EaRH1CXGd5+8NOw3uXgSwLzjO1VI1Cc3NioXyAVA/0vSyaJuki1M=
  app: cryptic-caverns-36094
  on:
    repo: alouie1020/uncrowd-me-client
